Feature
KamilGV/dp-2024-lab03 pull request #1
Opened 2024-10-31 14:31 UTC by KamilGV

2024-10-31 17:07 UTC, Rognak commented on Dockerfile
> +FROM python:3.9
3.11

2024-10-31 17:07 UTC, Rognak commented on requirements.txt
> +pytest~=8.3.3
Задублировалось

2024-10-31 17:08 UTC, Rognak commented on src/interfaces/IMessage.py
> +    def get_message(self) -> str:
Предлагаю сделать через property.

2024-10-31 17:08 UTC, Rognak commented on src/interfaces/IMessage.py
> +        pass
raise NotImplemented, так принято

2024-10-31 17:10 UTC, Rognak commented on src/message.py
> +    def __init__(self, message: str):
документация к аргументам

p.s. в формате sphinx

2024-10-31 17:13 UTC, Rognak commented on src/tests/test_messages.py
> +import datetime
Добавь тест, который проверит, что декораторы работают в совокупности

2024-10-31 17:13 UTC, Rognak requested changes
Поправь замечания, в остальном всё ок

2024-11-02 19:45 UTC, vladushka2000 commented on src/message.py
> +import base64
вынести в отдельную директорию

2024-11-02 19:47 UTC, vladushka2000 commented on src/message.py
> +        return "Добрый день,\n" + self._message.message
давай в отдельный метод вынесем создание сообщения. Я считаю, это не обязанность свойства по получению сообщения

2024-11-02 19:48 UTC, vladushka2000 commented on src/message.py
> +        print(self._message)
это необязательно, но попробуй сделать шаблонный метод. Тебе будет плюсом, на защите учту

2024-11-07 11:46 UTC, KamilGV commented on src/message.py
> +        return "Добрый день,\n" + self._message.message
вынес

2024-11-07 11:49 UTC, KamilGV commented on src/message.py
> +        print(self._message)
Не понял что нужно. Пока закрою.

2024-11-12 17:58 UTC, vladushka2000 approved these changes

2024-11-13 06:34 UTC, KamilGV commented
Реализована Лабораторная работа 3

2024-11-13 06:34 UTC, merged